name: Self Test

on: [push]

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Makepkg Build and Check
      id: makepkg
      uses: ./
      with:
        aurDeps: 1
    - name: Print Package Files
      run: |
        echo "Package: ${{ steps.makepkg.outputs.pkgfile0 }}"
