name: Self Test

on: [push]

jobs:
  # Test a package in a subdirectory
  pkgbuild-bonjour:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: "[Bonjour] Makepkg Build and Check"
      id: makepkg
      uses: ./
      with:
        pkgdir: "bonjour"
    - name: Print Package Files
      run: |
        echo "Package: ${{ steps.makepkg.outputs.pkgfile0 }}"
    - name: Upload Package Archive
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.makepkg.outputs.pkgfile0 }}
        path: ${{ steps.makepkg.outputs.pkgfile0 }}
