name: Self Test

on: [push]

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Makepkg Build and Check
      id: makepkg
      uses: ./
    - name: Print Package Files
      run: |
        echo "This PKGBUILD file creates two packages"
        echo "Package 0: ${{ steps.makepkg.outputs.pkgfile0 }}"
        echo "Package 1: ${{ steps.makepkg.outputs.pkgfile1 }}"
        echo "Package 2: ${{ steps.makepkg.outputs.pkgfile2 }}"
    - name: Upload Package Archive
      uses: actions/upload-artifact@v2
      with:
        path: ${{ steps.makepkg.outputs.pkgfile0 }}
